### ISSUE TITLE
Improve constraint preferences

### ISSUE THREAD

**Issue by CyboBrown** [JoshCunningHum/SchEdu#11]
Constraints should have a more user-friendly interface. Constraints should be set to max by default and a description should be provided, such as the following:

- **Max Instructor Minutes per Day** - The highest amount of time (in minutes) instructors are permitted to spend in classes each day.
- **Max Students Minutes per Day** - The highest amount of time (in minutes) students are permitted to spend in classes each day.
- **Max Room Minutes per Day** - The highest amount of time (in minutes) rooms can be used for classes each day.
- **Max Consecutive Minutes** - The highest amount of time (in minutes) that instructors may spend in class uninterrupted.

**Comment by JoshCunningHum** [comment]
6930f23f04827cf66386725eef7c11c822c32578

**Comment by JoshCunningHum** [comment]
cc9b159
