### ISSUE TITLE
Setting a class to online requires the class to be in an initial room

### ISSUE THREAD

**Issue by jethanSarita** [JoshCunningHum/SchEdu#12]
Creating a custom room named "online" and putting online classes there before setting it online on 4th step of the customization though it is redundant but it's the only way to do it. Current delulu is the online step is circumstantial to sudden changes in already assigned classes with rooms.

A potential work around to this is removing step 4 and adding a dedicated custom room. In order to avoid messiness and visual overlaps , create a layer system for classes of the same schedule.

Thinking about it now.. I think we're missing something here.. @_@ The necessity of a dedicated online room seems.. obsolete.. Mostly because I'm under the influence that my initial inputs and customization of the schedule.. Better safe than sorry though..

**Comment by JoshCunningHum** [comment]
Creating this "special room" will introduce more complexity and clutter in the UI. Hybrid classes are special cases. When classes are online, this scheduler is not needed, and there are more things that needs to be handled.
If there is a more effective way to do this than a special room with layers, I will consider refactoring the code.
