### ISSUE TITLE
Cannot add new room type

### ISSUE THREAD

**Issue by Goblinn02** [JoshCunningHum/SchEdu#2]
In the settings button
![image_2023-12-04_221118246](https://github.com/JoshCunningHum/SchEdu/assets/120450591/03b6e7cf-1599-482c-8c28-51eea6d58b9d)
, at category room type, man can't add new room type when pressing enter.

**Comment by JoshCunningHum** [comment]
hmmm unsa browser? so far mogana ra sa akoa. Make sure mag type ka sa input then enter, dili siya maka add if wala kay gi type

**Comment by Goblinn02** [comment]
okay2 its working now ah
