### ISSUE TITLE
Some teachers even though only assigned 1 course does not reflect on the timetable

### ISSUE THREAD

**Issue by jethanSarita** [JoshCunningHum/SchEdu#4]
![image](https://github.com/JoshCunningHum/SchEdu/assets/120331534/6f4982ab-a0c8-4a16-99ca-282c04ff24f6)
![image](https://github.com/JoshCunningHum/SchEdu/assets/120331534/3c58fd42-cb9a-4965-b05a-26c7e3a48f6a)
![image](https://github.com/JoshCunningHum/SchEdu/assets/120331534/4ccfa059-a0f4-4889-b075-7eaf2d80e3ef)
![image](https://github.com/JoshCunningHum/SchEdu/assets/120331534/7d3109c0-831d-42c4-9bb9-ed4c2e0e47ff)

**Comment by JoshCunningHum** [comment]
This should be fixed with the commit 68df18c00492b307d46066e179224f378d5e77b8. Will test later.
