### ISSUE TITLE
Customization issues part 1: the reckoning

### ISSUE THREAD

**Issue by jethanSarita** [JoshCunningHum/SchEdu#8]
Need dedicated online room that can stack same time as other schedules because it has virtually no space limit

Adding extra inputs/parameters (new rooms, teachers, etc..) whilst customizing existing generated timetable requires re-generating which erases customization progress

**Comment by JoshCunningHum** [comment]
> Adding extra inputs/parameters (new rooms, teachers, etc..) whilst customizing existing generated timetable requires re-generating which erases customization progress

This will not be worked on. It is not good to mix the outdated data with the latest data. Inconsistencies will happen from time to time.

https://github.com/JoshCunningHum/SchEdu/issues/5#issuecomment-1848358941

**Comment by JoshCunningHum** [comment]
Set to online room feature is added, will wait for tester approval (that's you)
c96c7a32b6552b0f31f6f17bf0f29df1313c0870
